# Auto-generated by Differentiable Inference Proxy
wells = [
    (15, 12, 37, "INJECTOR", 8000.0),
    (11, 12, 24, "INJECTOR", 8000.0),
    (44, 17, 51, "PRODUCER", -8000.0),
    (39, 37, 50, "PRODUCER", -8000.0),
    (10, 20, 50, "PRODUCER", -8000.0),
    (42, 23, 50, "PRODUCER", -8000.0),
    (2, 46, 50, "PRODUCER", -8000.0),
    (18, 24, 50, "PRODUCER", -8000.0),
    (61, 39, 41, "INJECTOR", 8000.0),
    (24, 32, 37, "INJECTOR", 8000.0),
    (62, 46, 28, "INJECTOR", 8000.0),
    (22, 57, 51, "INJECTOR", 8000.0),
]
