from __future__ import annotations

from typing import Any
import numpy as np
import h5py

def decode_h5_scalar(value: Any) -> Any:
    if isinstance(value, bytes):
        return value.decode("utf-8")
    if isinstance(value, np.bytes_):
        return value.astype(str)
    if isinstance(value, np.ndarray):
        if value.shape == ():
            return decode_h5_scalar(value.item())
        if value.size == 1:
            return decode_h5_scalar(value.reshape(-1)[0])
        return [
            decode_h5_scalar(v) for v in value.tolist()
        ]
    if isinstance(value, np.generic):
        return value.item()
    return value

def read_geology_metadata(src: h5py.File, geology_name: str) -> dict[str, Any]:
    metadata_group = None
    if "Metadata" in src:
        metadata_group = src["Metadata"]
    elif "metadata" in src:
        metadata_group = src["metadata"]

    def _read_key(key: str) -> Any:
        if metadata_group is None or key not in metadata_group:
            return None
        return decode_h5_scalar(metadata_group[key][()])

    rep_num = _read_key("RepNum")
    scenario_name = _read_key("ScenarioName")
    sample_num = _read_key("SampleNum")
    data_format_version = _read_key("DataFormatVersion")
    model_version = _read_key("ModelVersion")
    geology_config_id = rep_num if rep_num not in [None, ""] else scenario_name

    return {
        "geology_name": geology_name,
        "geology_config_id": geology_config_id,
        "rep_num": rep_num,
        "scenario_name": scenario_name,
        "sample_num": sample_num,
        "data_format_version": data_format_version,
        "model_version": model_version,
    }

def jl_quote(value: Any) -> str:
    s = "" if value is None else str(value)
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'

def sanitize_id_token(value: Any) -> str:
    text = "unknown" if value is None else str(value)
    out = []
    for c in text:
        if c.isalnum() or c in ["_", "-"]:
            out.append(c)
        else:
            out.append("_")
    token = "".join(out).strip("_")
    return token if token else "unknown"

def to_julia_wells_text(
    coords_xyz: np.ndarray,
    is_injector_list: list[bool],
    score: float,
    score_label: str,
    geology_revenue: list[float] | None = None,
    geology_energy: list[float] | None = None,
    geology_file: str | None = None,
    geology_name: str | None = None,
    geology_config_id: Any = None,
    geology_scenario_name: Any = None,
    geology_sample_num: Any = None,
    predicted_discounted_revenue: float | None = None,
    predicted_total_energy: float | None = None,
    ensemble_mean_revenue: float | None = None,
    ensemble_std_revenue: float | None = None,
    ensemble_member_revenues: list[float] | None = None,
    ensemble_labels: list[str] | None = None,
) -> str:
    lines = []
    lines.append("# Auto-generated by Differentiable Inference Proxy")
    lines.append(f"# {score_label}: {score:.6f}")
    if geology_revenue is not None:
        lines.append(
            "# Per-geology discounted revenue: "
            + ", ".join(f"{v:.6f}" for v in geology_revenue)
        )
    if geology_energy is not None:
        lines.append(
            "# Per-geology total energy: "
            + ", ".join(f"{v:.6f}" for v in geology_energy)
        )
    if ensemble_mean_revenue is not None:
        lines.append(f"# Ensemble mean discounted revenue: {ensemble_mean_revenue:.6f}")
    if ensemble_std_revenue is not None:
        lines.append(f"# Ensemble std discounted revenue: {ensemble_std_revenue:.6f}")
    if ensemble_member_revenues is not None:
        if ensemble_labels is None:
            ensemble_labels = [f"member_{i}" for i in range(len(ensemble_member_revenues))]
        lines.append("# Ensemble member discounted revenues:")
        for label, rev in zip(ensemble_labels, ensemble_member_revenues):
            lines.append(f"#   {label}: {rev:.6f}")

    if geology_file is not None:
        lines.append(f"# Geology file: {geology_file}")
    if geology_name is not None:
        lines.append(f"# Geology name: {geology_name}")
    if geology_config_id is not None:
        lines.append(f"# Geology config ID (Metadata/RepNum): {geology_config_id}")
    if geology_scenario_name is not None:
        lines.append(f"# Geology scenario name (Metadata/ScenarioName): {geology_scenario_name}")
    if geology_sample_num is not None:
        lines.append(f"# Geology sample number (Metadata/SampleNum): {geology_sample_num}")
    if predicted_discounted_revenue is not None:
        lines.append(
            f"# Predicted discounted revenue for this geology: {predicted_discounted_revenue:.6f}"
        )
    if predicted_total_energy is not None:
        lines.append(
            f"# Predicted total energy for this geology: {predicted_total_energy:.6f}"
        )

    if geology_config_id is not None:
        lines.append(f"geology_config_id = {jl_quote(geology_config_id)}")
    if geology_scenario_name is not None:
        lines.append(f"geology_scenario_name = {jl_quote(geology_scenario_name)}")
    if geology_file is not None:
        lines.append(f"geology_source_file = {jl_quote(geology_file)}")
    if geology_name is not None:
        lines.append(f"geology_source_name = {jl_quote(geology_name)}")

    lines.append("wells = [")
    for w, (x, y, z) in enumerate(coords_xyz):
        # Map continuous [X, Y, Z] to 1-based [I, J, K].
        # This mirrors the base differentiable inference export convention.
        j_idx = int(round(float(x))) + 1
        i_idx = int(round(float(y))) + 1
        k_idx = int(round(float(z))) + 1

        is_inj = is_injector_list[w]
        well_type = '"INJECTOR"' if is_inj else '"PRODUCER"'
        rate = 8000.0 if is_inj else -8000.0
        lines.append(f"    ({i_idx}, {j_idx}, {k_idx}, {well_type}, {rate}),")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)
