import argparse
from pathlib import Path
import numpy as np
import h5py
import sys
import csv
import random
import multiprocessing as mp
from functools import partial
from tqdm import tqdm

# allow importing from project root
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from geothermal.geology_graph import generate_geology_edges


def load_grids(h5_path: str, max_z: int = 70):
    with h5py.File(h5_path, "r") as src:
        perm_x = src["Input/PermX"][:max_z].astype(np.float32)
        perm_y = src["Input/PermY"][:max_z].astype(np.float32)
        perm_z = src["Input/PermZ"][:max_z].astype(np.float32)
        porosity = src["Input/Porosity"][:max_z].astype(np.float32)
        temp0 = src["Input/Temperature0"][:max_z].astype(np.float32)
        press0 = src["Input/Pressure0"][:max_z].astype(np.float32)
        is_well = src["Input/IsWell"][:max_z]
        inj_rate = src["Input/InjRate"][:max_z]

    perm_avg = (perm_x + perm_y + perm_z) / 3.0

    well_mask = is_well == 1
    has_well_xy = np.any(well_mask, axis=0)
    w_x, w_y = np.where(has_well_xy)
    n_wells = len(w_x)

    w_min_z = np.zeros(n_wells, dtype=np.int32)
    w_max_z = np.zeros(n_wells, dtype=np.int32)
    depth_centroid = np.zeros(n_wells, dtype=np.int32)
    is_injector = np.zeros(n_wells, dtype=bool)

    for i in range(n_wells):
        xi, yi = w_x[i], w_y[i]
        z_perf = np.where(well_mask[:, xi, yi])[0]
        if len(z_perf) == 0:
            continue

        w_min_z[i] = z_perf.min()
        w_max_z[i] = z_perf.max()
        w_inj_rate = inj_rate[w_max_z[i], xi, yi]
        is_injector[i] = w_inj_rate > 0

        if len(z_perf) <= 1:
            depth_centroid[i] = w_max_z[i]
        else:
            perms = perm_avg[z_perf, xi, yi].astype(np.float64)
            perms = np.maximum(perms, 1e-30)
            centroid_z = np.average(z_perf.astype(np.float64), weights=perms)
            depth_centroid[i] = z_perf[np.argmin(np.abs(z_perf - centroid_z))]

    well_grid_coords = np.stack([w_x, w_y, depth_centroid], axis=1)

    return perm_avg, porosity, temp0, press0, is_injector, well_grid_coords

def process_file(h5_path: Path, k_neighbors: int):
    try:
        perm_avg, porosity, temp0, press0, is_injector, well_grid_coords = load_grids(h5_path)
        
        # We want to evaluate all pairs generated by the A* knn logic.
        edge_index, edge_attr, path_coords_list = generate_geology_edges(
            perm_avg,
            porosity,
            temp0,
            press0,
            is_injector,
            well_grid_coords,
            k_neighbors=k_neighbors,
            return_paths=True,
        )

        if edge_index.shape[1] == 0:
            return [], f"{h5_path.name}: No A* paths generated with k_neighbors={k_neighbors}"

        results = []
        
        for path_idx in range(edge_index.shape[1]):
            u, v = edge_index[0, path_idx], edge_index[1, path_idx]
            path = path_coords_list[path_idx]
            
            # Start and end coordinates of the trajectory from well_grid_coords
            start_coord = well_grid_coords[u]
            end_coord = well_grid_coords[v]

            # Calculate bounding box of endpoints per dimension
            endpoints_dim_x = abs(start_coord[0] - end_coord[0])
            endpoints_dim_y = abs(start_coord[1] - end_coord[1])
            endpoints_dim_z = abs(start_coord[2] - end_coord[2])
            
            # Calculate bounding box per dimension
            min_vals = np.min(path, axis=0)
            max_vals = np.max(path, axis=0)
            dim_sizes = max_vals - min_vals

            # Diff of path bounding box vs endpoints bounding box
            diff_dim_x = dim_sizes[0] - endpoints_dim_x
            diff_dim_y = dim_sizes[1] - endpoints_dim_y
            diff_dim_z = dim_sizes[2] - endpoints_dim_z

            # Physical path length
            diffs = np.diff(path, axis=0)
            segment_lengths = np.sqrt(np.sum(diffs**2, axis=1))
            path_length = np.sum(segment_lengths)

            result = {
                "file": h5_path.name,
                "start_well": int(u),
                "goal_well": int(v),
                
                # Dimensions
                "path_dim_x": dim_sizes[0], "path_dim_y": dim_sizes[1], "path_dim_z": dim_sizes[2],
                "endpoints_dim_x": endpoints_dim_x, "endpoints_dim_y": endpoints_dim_y, "endpoints_dim_z": endpoints_dim_z,
                "diff_dim_x": diff_dim_x, "diff_dim_y": diff_dim_y, "diff_dim_z": diff_dim_z,
                
                "path_length": path_length
            }
            results.append(result)
            
        return results, None
    except Exception as e:
        return [], f"{h5_path.name}: {str(e)}"

def main():
    parser = argparse.ArgumentParser(description="Evaluate 3D bounding box for A* trajectories over HDF5 files.")
    parser.add_argument("--sample", type=str, help="Path to a single raw HDF5 file.")
    parser.add_argument("--folder", type=str, help="Directory containing .h5 files to process.")
    parser.add_argument("--num_samples", type=int, default=0, help="If using --folder, randomly sample this many files. 0 = all.")
    parser.add_argument("--k_neighbors", type=int, default=2, help="k_neighbors for A* procedure (default 2).")
    parser.add_argument("--num_workers", type=int, default=None, help="Number of parallel workers.")
    parser.add_argument("--output_csv", type=str, default="astar_bounding_boxes.csv", help="Path to output CSV file.")
    args = parser.parse_args()

    # Determine files to process
    files_to_process = []
    if args.sample:
        files_to_process.append(Path(args.sample))
    elif args.folder:
        folder_path = Path(args.folder)
        all_h5_files = list(folder_path.glob("*.h5"))
        if args.num_samples > 0 and len(all_h5_files) > args.num_samples:
            files_to_process = random.sample(all_h5_files, args.num_samples)
        else:
            files_to_process = all_h5_files
    else:
        print("Error: Must provide either --sample or --folder.")
        sys.exit(1)

    if not files_to_process:
        print("No files found to process.")
        sys.exit(0)

    if args.num_workers is None:
        num_workers = max(1, mp.cpu_count() - 1)
    else:
        num_workers = args.num_workers

    print(f"Processing {len(files_to_process)} files using {num_workers} workers...")
    
    all_results = []
    errors = []

    process_func = partial(process_file, k_neighbors=args.k_neighbors)
    with mp.Pool(processes=num_workers) as pool:
        for res_list, err in tqdm(
            pool.imap_unordered(process_func, files_to_process),
            total=len(files_to_process),
            desc="Evaluating A* Paths",
        ):
            if err:
                errors.append(err)
            else:
                all_results.extend(res_list)

    if not all_results:
        print("\nAll files failed or yielded no paths.")
        sys.exit(1)

    # Write to CSV
    fieldnames = [
        "file", "start_well", "goal_well", 
        "path_length",
        "path_dim_x", "path_dim_y", "path_dim_z",
        "endpoints_dim_x", "endpoints_dim_y", "endpoints_dim_z",
        "diff_dim_x", "diff_dim_y", "diff_dim_z"
    ]
    
    with open(args.output_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(all_results)

    print(f"\nSaved {len(all_results)} results to {args.output_csv}")
    
    if errors:
        print(f"\n{len(errors)} files had errors:")
        for err in errors[:5]:
            print(f"  - {err}")
        if len(errors) > 5:
            print(f"  - ... ({len(errors) - 5} more)")

if __name__ == "__main__":
    main()
